config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resource :questions, only: [:create]

  resource :answers, only: [:create]

  resource :likes, only: [:create, :destroy]

  get '/explore/(:username)', to: 'profile#search', as: 'explore'

  get '/me', to: 'profile#me', as: 'me'

  get '/profile/:username', to: 'profile#show', as: 'profile_show'

  get '/received_questions', to: 'questions#received_questions', as: 'received_questions'

  root 'home#index', as: 'home_index'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :likes
  has_one :addressee, through: :question

  scope :liked, -> { joins(:likes) }

  validates :content, :question_id, presence: true

  def liked_by?(user)
    likes.where(user: user).present?
  end

  def like_from(user)
    likes.find_by(user: user)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :answer
  belongs_to :user
  has_one :addressee, through: :answer

  validates :answer_id, :user_id, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :addressee, class_name: 'User'
  has_one :answer

  scope :answered,   -> { joins(:answer) }
  scope :unanswered, -> { left_outer_joins(:answer).where(answers: { id: nil }) }
  scope :anonymous,  -> { where(anonymous: true) }

  validates :content, :sender_id, :addressee_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :submitted_questions, class_name: 'Question', foreign_key: 'sender_id'
  has_many :received_questions, class_name: 'Question', foreign_key: 'addressee_id'
  has_many :likes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :name, presence: true
  validates :username, uniqueness: true

  def answered_questions
    received_questions.answered.joins(:sender).includes(:sender)
  end

  def unanswered_questions
    received_questions.unanswered.joins(:sender).includes(:sender)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to received_questions_path, notice: 'Question successfully answered.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { redirect_to received_questions_path, alert: 'Oops! Something went wrong... Make sure to write something to answer.' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def render_not_found
    render file: '/public/404.html.erb', status: 404
  end

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  private

  # Overwriting the sign_in redirect path method
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || me_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name])
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if user_signed_in?
      redirect_to me_path
    else
      render layout: false
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:destroy]

  def create

    @like = current_user.likes.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_back(fallback_location: profile_show_path(@like.addressee.username), notice: 'Liked!') }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { redirect_back(fallback_location: profile_show_path(@like.addressee.username), alert: 'Oops... something went wrong! Reload the page and try again.') }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html {  redirect_back(fallback_location: profile_show_path(@like.addressee.username), notice: 'Unliked!') }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_like
    @like = Like.find(like_params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def like_params
    params.require(:like).permit(:answer_id, :id)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def me
    @user = current_user
    render 'show'
  end

  def show
    @user = User.find_by(username: params[:username])
    render_not_found if @user.nil?
  end

  # GET /explore
  def search
    @users = User.where('username like ?', "%#{params[:username]}%") if params[:username].present?
    @message = "Nothing found" if @users.try(:empty?)
    @message = "Type username to search" if params[:username] == ''
    render 'explore'
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]

  # GET /received_questions
  def received_questions; end

  def create
    @question = current_user.submitted_questions.new(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_back(fallback_location: profile_show_path(username: @question.addressee.username), notice: 'Question was successfully sent.') }
        format.json { render :show, status: :created, location: @question }
        WebNotificationsChannel.broadcast_to(
            @question.addressee,
            body: 'You received a new question!'
        )
      else
        format.html { redirect_back(fallback_location: profile_show_path(username: @question.addressee.username), alert: 'Oops! Something went wrong... Make sure to write something to send.') }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:sender_id, :addressee_id, :content, :anonymous)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /explore
  def explore; end

  # POST /explore
  def find_user
    @users = User.where('username like ?', "%#{user_params[:username]}%")
    # @results = @users.size
    render 'explore'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
  def like_form_options(answer)
    if answer.liked_by?(current_user)
      method = :delete
      like = answer.like_from(current_user)
      button_class = 'btn-like-red'
    else
      method = :post
      like = Like.new
      button_class = 'btn-like-gray'
    end

    { like: like, answer: answer, method_form: method, button_class: button_class }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true, class: 'form-ccc') do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :question_id, value: question.id, id: :answer_question, class: 'form-control' %>

  <div class="form-group">
    <%= form.label :content, 'Answer the question:' %>
    <%= form.text_area :content, id: :answer_content, class: 'form-control' %>
  </div>

  <br>
  <div class="form-group text-right">
    <%= form.submit 'Answer', class: 'btn btn-lg btn-danger' %>
  </div>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuriouscatcloneRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Amaranth|Viga">
  </head>

  <body>
    <div class="container full-screen">
      <div class="middle-fullscreen">
        <div class="row">
          <div class="col-md-4 offset-md-2 box-home text-center">
            <h1>Welcome!</h1>
            <h2> <%= link_to 'Login', new_user_session_path %></h2>
            <h2> <%= link_to 'Register', new_user_registration_path %></h2>
          </div>
          <div class="col-md-4">
            <%= image_tag ("/assets/ccc.png"), class: "w-100"%>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuriouscatcloneRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Amaranth|Viga|Rajdhani ">

    <!-- JavaScript -->
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.11.3/build/alertify.min.js"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.3/build/css/alertify.min.css"/>
  </head>

<body>
  <nav id="navbar-ccc" class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to home_index_path, class: "navbar-brand" do%>
        <%= image_tag ('/assets/navbar.png'), class: 'img-nav' %>
      <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-auth" aria-controls="nav-auth" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="nav-auth">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Home', me_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Explore', explore_path, class:"nav-link"%>
          </li>
          <li class="nav-item ">
            <%= link_to 'Received Questions', received_questions_path, class: "nav-link" %>
          </li>
          <li class="nav-item ">
            <span class="badge badge-pill badge-danger"><%= current_user.unanswered_questions.size %></span>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container alert-app">
    <% if notice %>
      <div class="alert alert-success  alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>

  <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: like, url: likes_path, method: method_form) do |form| %>

  <%= form.hidden_field :id, value: like.id, id: :likes_id, class: 'form-control' %>
  <%= form.hidden_field :answer_id, value: answer.id, id: :likes_answer, class: 'form-control' %>
    <button type="submit" name="commit" class="btn-like <%= button_class %>"><%= fa_icon 'heart', class: 'gray' %></button>
<% end %>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true, class: 'form-ccc') do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :addressee_id, value: addressee.id, id: :question_addressee, class: 'form-control' %>

  <div class="form-group">
    <%= form.label :content, 'Send a question' %>
    <%= form.text_area :content, id: :question_content, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= form.check_box :anonymous, id: :question_anonymous, class: 'form-check-input' %>
    <%= form.label :anonymous, 'Send anonymously', class: 'form-check-label' %>
  </div>


  <div class="form-group text-right">
    <%= form.submit 'Send', class: 'btn btn-lg btn-danger' %>
  </div>
<% end %>

app/views/questions/received_questions.html.erb
<div class="container received-questions">
  <h1 class="title">Received Questions</h1>

  <% current_user.unanswered_questions.each do |question| %>
    <div class="list-received-questions">
      <div class="row">
        <div class="col">
          <small class="text-muted">
            <em>Sent by&nbsp;</em>
            <% if question.anonymous %>
              anonymous
            <% else %>
              <a href="<%= profile_show_path(username: question.sender.username) %>">
                <%= question.sender.username %>
              </a>
            <% end %>
          </small>
          <h1><%= question.content %></h1>

          <%= render 'answers/form', answer: Answer.new, question: question %>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.unanswered_questions.empty? %>
    <div class="row profile">
      <div class="col text-center">
        <p class="empty-message">Nothing to see <span>here</span>.</p>
      </div>
    </div>
  <% end %>

</div>

app/views/users/_form_explore.html.erb
<%= form_with(model: user, local: true, class: 'form-ccc') do |form| %>
  <div class="input-group">
    <%= form.text_field :username, id: :user_username, class: 'form-control', placeholder: 'Type the username here...', autofocus: 'autofocus' %>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-ccc-search">
          <%= fa_icon "search" %>
      </button>
    </span>
  </div>
<% end %>

app/views/users/explore.html.erb
<div class="container users">
  <div class="row">
    <div class="col-md-12">
      <h1>Explore</h1>

      <%= render 'form_explore' , user: User.new%>
    </div>
  </div>

  <br><br>

  <div class="row">
    <div class="col">
<%= @users.present? %>
<%= @results.present? %>
    <% if @results.present? %>
      <h3>Search result...</h3>
      <br>

      <% if @results > 0 %>
        <table class="table table-striped">
          <tbody>

          <%@users.each do |user| %>
          <tr>
            <td>
              <a href="<%= profile_show_path(username: user.username) %>">
                <p><strong>/<%= user.username %></strong></p>
                <p class="text-muted"><%= user.name %></p>
              </a>
            </td>
          </tr>
          <% end %>

          </tbody>
        </table>

      <% else %>
          <div class="alert  text-center">Nothing found.</div>

      <% end %>

    <% end %>

    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %><%= link_to "Forgot your password?", new_password_path(resource_name) %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>